// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suzbpqdwrzqydsozlele.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1emJwcWR3cnpxeWRzb3psZWxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzNjQ1MzksImV4cCI6MjA0OTk0MDUzOX0.PWI1Oa8gngbsmmPlaoHJumU8_Hs9M_uZyjjFo_UJswg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);